#!/usr/bin/env python3
"""Write the interactive exercises (chapters/_NN-interactive.qmd).

Each chapter gets 4-5 sort / order / pick widgets, rendered by
includes/interactive.html (the engine shared with the GRC1100 script).
The exercises are drawn from the chapter's own tables and definitions, so
every one of them is answerable from the chapter text. tools/tex2qmd.py
includes the file in the chapter's "Interactive exercises" section.

Widget configs (see includes/interactive.html):
  sort:  buckets [{id,label,desc}], chips [{t,b}]   (b=None -> distractor)
  order: steps [...], hint
  pick:  options [{t,ok}], prompt
plus explain / ref / reflabel shown after a correct answer.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

SLUGS = {
    1: "introduction", 2: "approaches-to-research", 3: "purpose-and-products",
    4: "research-questions", 5: "reviewing-the-literature",
    6: "strategies-survey-design-experiment", 7: "strategies-case-action-ethnography",
    8: "quantitative-data", 9: "qualitative-data", 10: "ethics",
    11: "producing-the-essay", 12: "summing-up",
}


def sort(title, intro, buckets, chips, explain, ref, reflabel):
    return dict(type="sort", title=title, intro=intro,
                cfg=dict(buckets=[dict(id=b[0], label=b[1], **({"desc": b[2]} if len(b) > 2 else {})) for b in buckets],
                         chips=[dict(t=t, b=b) for t, b in chips],
                         explain=explain, ref=ref, reflabel=reflabel))


def order(title, intro, steps, explain, ref, reflabel, hint=None):
    cfg = dict(steps=steps, explain=explain, ref=ref, reflabel=reflabel)
    if hint:
        cfg["hint"] = hint
    return dict(type="order", title=title, intro=intro, cfg=cfg)


def pick(title, intro, options, explain, ref, reflabel, prompt=None):
    cfg = dict(options=[dict(t=t, ok=ok) for t, ok in options], explain=explain, ref=ref, reflabel=reflabel)
    if prompt:
        cfg["prompt"] = prompt
    return dict(type="pick", title=title, intro=intro, cfg=cfg)


EX = {
1: [
    sort("Science and pseudo-science", "Drag each mark to the side it belongs to.",
         [("sci", "Science"), ("pseudo", "Pseudo-science")],
         [("Revises its claims when evidence contradicts them", "sci"),
          ("Makes risky, checkable predictions", "sci"),
          ("States its own limits and uncertainty", "sci"),
          ("Immune to evidence — always the same answer", "pseudo"),
          ("Explains everything after the fact", "pseudo"),
          ("Claims certainty", "pseudo")],
         "The distinguishing mark of science is not being right but changing in response to evidence.",
         "sec-01-what-research-is", "What research is"),
    order("The information supply chain", "Click the stations of the supply chain in order, from where a finding is produced to where most claims reach us.",
          ["Original studies", "Syntheses", "Professional layer", "Media", "Feeds"],
          "Reach and speed increase along the chain; quality control and detail decrease. The task is to trace a claim back to the left.",
          "sec-01-what-research-is", "Three claims and one question",
          hint="click the stations, from original studies to feeds"),
    pick("The three conditions of research", "Select the conditions that the working definition of research requires.",
         [("An original contribution", True), ("A systematic process", True), ("Openness to criticism", True),
          ("A large sample", False), ("A positive result", False), ("A vendor sponsor", False)],
         "Remove any one of the three conditions and what remains is no longer research: a penetration-test report, for instance, is systematic and documented but rarely original.",
         "sec-01-what-research-is", "A working definition"),
    sort("Development project or research project?", "The same project, twice: sort each statement to the version it describes.",
         [("dev", "Development project"), ("res", "Research project")],
         [("We build a password-manager onboarding flow for the client", "dev"),
          ("We build the flow — and investigate where users abort, and why", "res"),
          ("Success = it ships and works", "dev"),
          ("Success = it ships and we can say something new and evidenced about drop-off", "res"),
          ("Report: what we built and how", "dev"),
          ("Report: what we built, how we studied it, what we found, what it means beyond this client", "res")],
         "The research version is more useful to the client, not less, because it explains why the numbers move.",
         "sec-01-reading-material", "Reading material"),
    pick("What research is not", "Which of these, on its own, is not research?",
         [("\"I built a tool and it works\"", True), ("\"I searched the web and summarised\"", True),
          ("\"Our penetration test found 12 vulnerabilities\"", True), ("\"Everyone on the team agrees\"", True),
          ("A systematic study whose method and findings others can evaluate", False)],
         "A tool without a question, a summary of opinions, a client report and a consensus each lack at least one of the three conditions.",
         "sec-01-worked-examples-and-tables", "What research is not"),
],
2: [
    sort("Quantitative, qualitative or mixed?", "Classify each study description by its approach.",
         [("quant", "Quantitative", "numbers, variables, testing"), ("qual", "Qualitative", "words, meanings, exploring"), ("mixed", "Mixed methods", "both kinds of data, integrated")],
         [("A survey of 500 app users: which factors predict abandonment?", "quant"),
          ("Twelve interviews: how do people experience abandoning an app?", "qual"),
          ("A survey first, then interviews with a sample of those who quit", "mixed"),
          ("Six months of telemetry logs modelled to predict churn", "quant"),
          ("Three weeks in a security operations centre, then eight interviews", "qual"),
          ("A questionnaire (n = 412), then ten interviews on an unexpected result", "mixed")],
         "Closed-ended data and testing are quantitative; open-ended data and meaning are qualitative; a study that integrates both is mixed.",
         "sec-02-three-approaches", "Three approaches"),
    order("The research onion, from the outside in", "Click the six layers of the onion in the order in which they are read.",
          ["Philosophy", "Approach to theory development", "Methodological choice", "Strategy", "Time horizon", "Techniques and procedures"],
          "The outer layers constrain the inner ones: an interpretivist philosophy combined with a large-scale survey needs explaining.",
          "sec-02-worldviews", "The research onion",
          hint="click the layers, outermost first"),
    sort("Four worldviews", "Place each example or description on Creswell's worldview it belongs to.",
         [("post", "Postpositivism"), ("con", "Constructivism"), ("trans", "Transformative"), ("prag", "Pragmatism")],
         [("A/B test: which onboarding flow reduces app churn?", "post"),
          ("Interviews: what does \"secure enough\" mean to small-business sysadmins?", "con"),
          ("Co-designing an accessible web frontend with visually impaired users", "trans"),
          ("Mixed-methods evaluation of a password manager", "prag"),
          ("Knowledge is objective; found by measuring and testing causes", "post"),
          ("Knowledge is whatever works to solve the problem", "prag")],
         "Postpositivism measures and tests, constructivism reconstructs meaning, the transformative worldview aims at change, pragmatism lets the question decide.",
         "sec-02-worldviews", "Worldviews"),
    pick("Deductive reasoning", "Select the steps that belong to a deductive, theory-testing study.",
         [("Theory first, then a hypothesis", True), ("Data collection to test the hypothesis", True),
          ("Confirm or reject the hypothesis with statistics", True),
          ("Themes condensed from open interviews", False), ("Patterns (codes) found in the data first", False),
          ("A model of the phenomenon built as the outcome", False)],
         "Deduction runs theory → hypothesis → data → confirm or reject; induction runs data → patterns → themes → theory.",
         "sec-02-worked-examples-and-tables", "Deductive and inductive reasoning"),
],
3: [
    sort("The 6Ps in the essay", "Where does each P appear in the essay? Drag it to the part.",
         [("p1", "Part I", "problem, aim, question"), ("p23", "Parts II–III", "literature, strategy, methods"), ("p4", "Part IV", "data, ethics, participants"), ("doc", "The document itself")],
         [("Purpose", "p1"), ("Process", "p23"), ("Paradigm", "p23"), ("Participants", "p4"), ("Presentation", "doc")],
         "Purpose sits in Part I; process and paradigm in Parts II–III; participants (ethics, SIKT, who provides data) in Part IV; presentation is the ten-page document.",
         "sec-03-the-6ps", "The 6Ps"),
    pick("Purpose statements that work", "Select the purpose statements that have a problem, an owner and a so-that.",
         [("to study why developers ignore security warnings so that tooling can be redesigned", True),
          ("to identify onboarding steps where password-manager users abort, so that the client can prioritise fixes", True),
          ("to look into cyber security in companies", False),
          ("to make the client's website better", False),
          ("to prove that TypeScript reduces bugs", False)],
         "A purpose statement is one sentence: to (find out X) so that (Y benefits). \"Prove\" presumes the answer; \"better\" is a goal, not a purpose.",
         "sec-03-purpose", "Purpose"),
    order("The funnel", "Click the stages of the funnel in order, from the widest to the narrowest.",
          ["Topic", "Problem", "Purpose", "Research question"],
          "A topic is a broad area of interest; a problem is something wrong, unknown or needed with an owner and a cost; the purpose says what the study will find out and for whom; the question follows.",
          "sec-03-purpose", "From topic to problem to purpose",
          hint="click the stages, widest first"),
    sort("Research or standards?", "Two systems of knowledge production: sort each property to the system it describes.",
         [("res", "Research"), ("std", "Standards and practice")],
         [("Descriptive, explanatory claims", "res"), ("Prescriptive, normative claims", "std"),
          ("Validation by evidence, replication, peer review", "res"), ("Validation by consensus, voting, uptake", "std"),
          ("Generalisation is the aim", "res"), ("Applicability is the aim", "std"),
          ("Failure means the hypothesis is rejected", "res"), ("Failure means the standard is not adopted", "std")],
         "Standards are normatively binding without having been tested empirically; research generalises and corrects itself by refutation.",
         "sec-03-two-systems-of-knowledge-production", "Two systems of knowledge production"),
    sort("Types of contribution", "Match each example to the type of contribution it makes.",
         [("prod", "Product"), ("theory", "Theory or model"), ("method", "Method"), ("evid", "Evidence"), ("synth", "Synthesis")],
         [("an accessible component library, evaluated", "prod"),
          ("a model of why developers ignore security warnings", "theory"),
          ("a lighter threat-modelling method for small teams", "method"),
          ("measured effect of security warnings on click-through", "evid"),
          ("systematic review of passkey adoption studies", "synth")],
         "The output is the thing produced; the contribution is what the world knows or can do now.",
         "sec-03-products", "Products"),
],
4: [
    sort("The four layers of a question", "Sort the password-reuse examples to the layer each one belongs to.",
         [("aim", "Aim"), ("obj", "Objective"), ("rq", "Research question"), ("hyp", "Hypothesis")],
         [("understand why employees reuse passwords", "aim"),
          ("survey 150 employees; interview 8 of them", "obj"),
          ("which factors are associated with password reuse among SMB employees?", "rq"),
          ("H1: perceived account value is negatively associated with reuse", "hyp")],
         "The aim is the overall intent, objectives are checkable steps, the research question is what the study answers, a hypothesis is a testable predicted answer.",
         "sec-04-anatomy", "Anatomy"),
    sort("Question types", "Descriptive, comparative or relationship: sort the questions and templates.",
         [("desc", "Descriptive"), ("comp", "Comparative"), ("rel", "Relationship")],
         [("how widespread is password reuse among SMB employees?", "desc"),
          ("do developers with security training reuse passwords less than those without?", "comp"),
          ("does perceived account value affect password reuse?", "rel"),
          ("how frequent or large is X in group G?", "desc"),
          ("does group A differ from group B on X?", "comp"),
          ("is X associated with Y?", "rel")],
         "The shape of the question already implies the data: a count, a comparison of groups, or a measured association.",
         "sec-04-question-types", "Question types"),
    sort("The five failure modes", "Drag each draft question to its failure mode.",
         [("broad", "Too broad"), ("triv", "Trivial yes/no"), ("nores", "Not researchable"), ("double", "Double-barreled"), ("assum", "Assumption baked in")],
         [("\"How can cyber security be improved?\"", "broad"),
          ("\"Is phishing dangerous?\"", "triv"),
          ("\"Should companies be punished for breaches?\"", "nores"),
          ("\"How do users choose passwords and why do they reuse them?\"", "double"),
          ("\"Why does TypeScript make teams faster?\"", "assum")],
         "A career, not a study; answerable without data; a value judgement; two studies in one; an effect presumed rather than investigated.",
         "sec-04-from-bad-to-good", "From bad to good"),
    order("PICO", "Click the four slots of PICO in order.",
          ["Population", "Intervention", "Comparison", "Outcome"],
          "Four slots turn a vague comparison idea into a complete question: SMB employees; quarterly phishing simulations; annual e-learning; click-through rate.",
          "sec-04-worked-examples-and-tables", "PICO and GQM",
          hint="click P, I, C, O"),
    pick("Testable hypotheses", "Select the hypotheses that are testable as stated.",
         [("H1: employees with security training reuse fewer passwords than those without", True),
          ("H3: perceived account value is negatively associated with reuse", True),
          ("H2: the new warning design is better", False),
          ("Is phishing dangerous?", False)],
         "Testable means two groups or named variables, a measurable outcome and a stated direction; \"better\" has no measure or direction.",
         "sec-04-worked-examples-and-tables", "Hierarchies and hypotheses"),
],
5: [
    order("The five phases of a literature review", "Click the phases in order.",
          ["Review scope", "Conceptualisation", "Search process", "Analysis and synthesis", "Research agenda"],
          "Scope and concepts come before the search; extraction by concept comes after it; the agenda is what remains open — and therefore your study.",
          "sec-05-worked-examples-and-tables", "The five phases, walked through"),
    sort("Source types", "What is each kind of source good for? Drag it to its use.",
         [("core", "Core evidence"), ("concepts", "Concepts and methods"), ("grey", "Practice context — flag as grey"), ("leads", "Leads only — verify elsewhere")],
         [("Peer-reviewed journals (IEEE TSE, Computers & Security)", "core"),
          ("Conference proceedings (ICSE, CHI, USENIX Security)", "core"),
          ("Books and textbooks", "concepts"),
          ("Standards and industry reports (NIST, OWASP, Verizon DBIR)", "grey"),
          ("Engineering blogs and vendor pages", "leads")],
         "Conference proceedings are core evidence in computing; grey literature gives practice context and must be flagged as such.",
         "sec-05-where-to-look", "Where to look"),
    sort("Boolean operators", "Sort each effect to the operator that produces it.",
         [("and", "AND"), ("or", "OR"), ("not", "NOT")],
         [("narrows the search", "and"), ("widens the search", "or"), ("excludes — use carefully", "not"),
          ("combines the concepts of the question", "and"), ("joins the synonyms within one concept", "or")],
         "Synonyms within a concept are joined with OR; the concepts of the question are combined with AND.",
         "sec-05-systematic-search", "Systematic search"),
    order("From question to argument", "Click the artefacts of Part II in the order in which they are produced.",
          ["Keyword table", "Search string and log", "Criteria and PRISMA", "Concept matrix", "Four moves"],
          "Five artefacts, and Part II assembles itself around them; the most common gap is a matrix whose moves were never written.",
          "sec-05-read-and-synthesise", "Read and synthesise",
          hint="click the artefacts, first one first"),
    pick("The concept matrix", "Select the statements that describe a concept matrix.",
         [("Concepts as columns", True), ("Papers as rows", True),
          ("A cell marks that a paper addresses the concept", True),
          ("One paper summarised per paragraph", False), ("Sorted by publication year", False)],
         "Extract by concept, not by paper: the matrix is the synthesis table of Webster and Watson.",
         "sec-05-read-and-synthesise", "Reading and the concept matrix"),
],
6: [
    sort("Which strategy?", "Sort each core idea and question shape to its strategy.",
         [("survey", "Survey"), ("dc", "Design and creation"), ("exp", "Experiment")],
         [("the same questions to many, systematically", "survey"),
          ("build an IT artefact — and learn from building and evaluating it", "dc"),
          ("manipulate a cause, measure the effect, control the rest", "exp"),
          ("how widespread is X / which factors are associated", "survey"),
          ("can X be built — and how well does it work", "dc"),
          ("does A cause B", "exp")],
         "The question's wording points to the strategy, and each strategy has its price: respondents, build skills plus an evaluation plan, or control and randomisation.",
         "sec-06-the-menu", "The menu"),
    order("The design and creation cycle", "Click the five steps of the cycle in order.",
          ["Awareness", "Suggestion", "Development", "Evaluation", "Conclusion"],
          "Awareness of the problem, a tentative design idea, building the artefact, evaluating it (does it work? how well? for whom?), and consolidating what was learned — with iteration back to suggestion.",
          "sec-06-design-and-creation", "Design and creation"),
    sort("Development project or design and creation research?", "Sort each statement to the kind of project it describes.",
         [("dev", "Development project"), ("res", "Design and creation research")],
         [("goal: a working system", "dev"), ("goal: knowledge, demonstrated via the artefact", "res"),
          ("requirements from a client", "dev"), ("problem grounded in literature", "res"),
          ("testing: does it work?", "dev"), ("evaluation: how well, for whom, compared to what — with a method", "res"),
          ("report: what we built", "dev"), ("report: what we learned, transferable beyond this system", "res")],
         "The research lives in the evaluation: how well, for whom, compared to what, with a method.",
         "sec-06-worked-examples-and-tables", "Design and creation — the cycle and the evaluation"),
    sort("Sampling vocabulary", "Match each description to the sampling term.",
         [("pop", "Population"), ("frame", "Sampling frame"), ("prob", "Probability sampling"), ("nonprob", "Non-probability sampling")],
         [("everyone your answer should apply to (e.g. SMB employees in Norway)", "pop"),
          ("the actual list you can draw from (e.g. employees of six partner firms)", "frame"),
          ("random selection — allows statistical generalisation", "prob"),
          ("convenience, snowball, purposive — honest label required", "nonprob")],
         "Convenience sampling is legitimate if it is named and its limits are discussed.",
         "sec-06-survey", "Survey"),
    sort("Internal or external validity?", "Sort each statement to the kind of validity it concerns.",
         [("int", "Internal validity"), ("ext", "External validity")],
         [("the manipulation, not something else, caused the effect", "int"),
          ("the effect holds outside the study setting", "ext"),
          ("randomisation and a control group protect it", "int"),
          ("a laboratory task with students threatens it", "ext")],
         "Only the experiment's design — randomisation, control — licenses the word because; whether the effect travels is a separate question.",
         "sec-06-experiment", "Experiment"),
],
7: [
    sort("Which strategy fits?", "Sort each question shape and requirement to the strategy.",
         [("case", "Case study"), ("action", "Action research"), ("ethno", "Ethnography")],
         [("how or why does it happen in this setting", "case"),
          ("how can this practice be improved — and why does it work", "action"),
          ("what are the unwritten rules of this group", "ethno"),
          ("deep access to one setting", "case"),
          ("a client willing to change; at least two cycles", "action"),
          ("time, immersion, access", "ethno")],
         "Depth in one setting, change in cycles with the practitioners, or immersion to find the unwritten rules.",
         "sec-07-the-decision", "The decision"),
    order("One action-research cycle", "Click the four steps of a cycle in order.",
          ["Plan", "Act", "Observe", "Reflect"],
          "Rigour requires at least two cycles, documented honestly rather than as a success story.",
          "sec-07-action-research", "Action research"),
    sort("Design and creation or action research?", "The common confusion: sort each property to the strategy.",
         [("dc", "Design and creation"), ("ar", "Action research")],
         [("centre of gravity: the artefact", "dc"), ("centre of gravity: the practice or organisation", "ar"),
          ("what is evaluated: how well the artefact works", "dc"), ("what is evaluated: how the practice changed", "ar"),
          ("users evaluate", "dc"), ("practitioners co-drive the change", "ar"),
          ("output: artefact plus evaluation knowledge", "dc"), ("output: documented change across cycles", "ar")],
         "In design and creation the artefact is the centre of gravity; in action research it is the practice, changed together with the practitioners.",
         "sec-07-worked-examples-and-tables", "Action research — example, assessment, and the common confusion"),
    pick("The mismatch clinic", "Select the question–strategy pairings that fail.",
         [("\"How do admins experience audits?\" + survey", True),
          ("\"Does caching reduce latency?\" + case study", True),
          ("\"How widespread is MFA adoption?\" + ethnography", True),
          ("\"Does caching reduce latency?\" + experiment", False),
          ("\"How widespread is MFA adoption?\" + survey", False)],
         "Experience questions need depth, causal claims need manipulation and control, prevalence questions need breadth.",
         "sec-07-worked-examples-and-tables", "Mismatch clinic and the fit of all six"),
],
8: [
    sort("Levels of measurement", "Sort the examples and summaries to the level of measurement.",
         [("nom", "Nominal"), ("ord", "Ordinal"), ("int", "Interval"), ("ratio", "Ratio")],
         [("OS: Windows / macOS / Linux", "nom"), ("Likert 1–5; severity low–high", "ord"),
          ("temperature in °C", "int"), ("response time in ms; count of alerts", "ratio"),
          ("mode, frequencies", "nom"), ("median, distribution", "ord")],
         "The level decides the legal operations: count and compare, rank, differences, or everything including ratios.",
         "sec-08-levels-of-measurement", "Levels of measurement"),
    sort("Which test?", "Match each situation to the test that fits it.",
         [("t", "t-test"), ("chi", "chi-square"), ("corr", "correlation")],
         [("compare two group means", "t"), ("compare frequencies across categories", "chi"),
          ("association of two numeric variables", "corr"),
          ("fatigue-scale mean: trained vs. untrained employees", "t"),
          ("clicked / didn't click × warning A / B", "chi"),
          ("fatigue score vs. reported reuse score", "corr")],
         "The reasoning is what Part IV wants: the test name alone is a guess; the because shows you matched test to data type.",
         "sec-08-analysis", "Analysis"),
    sort("Item wording failures", "Drag each broken item to its failure.",
         [("lead", "Leading"), ("double", "Double-barreled"), ("jargon", "Jargon"), ("vague", "Vague quantifiers"), ("memory", "Memory overreach")],
         [("\"Don't you agree that MFA is important?\"", "lead"),
          ("\"Is the app fast and easy to use?\"", "double"),
          ("\"How often do you rotate credentials?\"", "jargon"),
          ("\"Do you often reuse passwords?\"", "vague"),
          ("\"How many phishing mails did you get last year?\"", "memory")],
         "Each failure has a repair: a neutral scale, two items, plain words, a countable answer, a shorter recall window.",
         "sec-08-questionnaires", "Questionnaires"),
    pick("p-values and effect sizes", "Select the statements that are true.",
         [("A p-value is the probability of data at least this extreme, assuming no real effect", True),
          ("Report the effect size together with p", True),
          ("With n = 24,000, p < .001 can go with a difference of 0.4 percentage points", True),
          ("A tiny p-value proves a large effect", False),
          ("A survey correlation licenses the word \"because\"", False)],
         "Significance is not size: the same small difference becomes significant with a large enough sample, and only the experiment's design licenses because.",
         "sec-08-analysis", "Analysis"),
    sort("PLS-SEM or CB-SEM?", "Sort each property to the kind of structural equation modelling.",
         [("pls", "PLS-SEM"), ("cb", "CB-SEM")],
         [("prediction and exploration; maximises explained variance", "pls"),
          ("theory testing; reproduces the covariance matrix", "cb"),
          ("works with smaller samples and non-normal data", "pls"),
          ("needs larger samples and near-normal data", "cb"),
          ("SmartPLS", "pls"), ("AMOS, lavaan (R), Mplus", "cb")],
         "Grassini et al. (2024) and Jo & Park (2024) use PLS-SEM; Huy et al. (2024) use CB-SEM.",
         "sec-08-adoption-surveys-utaut2-and-pls-sem", "Adoption surveys, UTAUT2 and PLS-SEM"),
],
9: [
    order("Thematic analysis", "Click the five steps in order.",
          ["Familiarise", "Code", "Build themes", "Review", "Define and write"],
          "Read all transcripts first; label segments close to the words; group codes into themes; check the themes against all data; name them and evidence them with quotes.",
          "sec-09-analysis", "Analysis"),
    sort("Interview questions: broken or repaired?", "Sort the questions.",
         [("broken", "Broken"), ("rep", "Repaired")],
         [("Don't you find security policies annoying?", "broken"),
          ("How do the security policies affect your daily work?", "rep"),
          ("Do you follow the password policy? (yes/no)", "broken"),
          ("Tell me about the last time the password policy got in your way.", "rep"),
          ("Why is your team bad at reviews?", "broken"),
          ("How do reviews typically go in your team?", "rep")],
         "Repaired questions are open, neutral and anchored in a concrete episode rather than an opinion.",
         "sec-09-interviews", "Interviews"),
    sort("Code or theme?", "Sort each label to the level of analysis it belongs to.",
         [("code", "Code", "close to the words"), ("theme", "Theme", "an interpretation across the data")],
         [("reactive patching", "code"), ("cost framing by management", "code"), ("incident as trigger", "code"),
          ("security as time negotiation", "theme"), ("external events drive priority", "theme"),
          ("accessibility is invisible work", "theme")],
         "A code is a short label for a meaningful segment; a theme groups codes across the data into an interpretation.",
         "sec-09-worked-examples-and-tables", "Thematic analysis — process, coding, quality"),
    sort("Information power", "Which dimension calls for fewer participants, which for more?",
         [("fewer", "Fewer participants"), ("more", "More participants")],
         [("narrow study aim", "fewer"), ("broad study aim", "more"),
          ("dense sample: participants hold exactly the experience sought", "fewer"),
          ("established theory applied", "fewer"),
          ("cross-case analysis", "more"), ("weak quality of dialogue", "more")],
         "The more information the sample holds, the fewer participants are needed.",
         "sec-09-the-qualitative-data-plan", "The qualitative data plan"),
    sort("Field notes: descriptive or interpretive?", "Sort each note to its column.",
         [("desc", "Descriptive", "what happened"), ("interp", "Interpretive", "what I make of it")],
         [("10:14 — build fails on security scan; A adds an ignore flag without opening the finding", "desc"),
          ("suppression is routinised — no discussion needed", "interp"),
          ("B asks A \"real one?\"; A shrugs: \"same as always\"", "desc"),
          ("a shared classification exists that no document defines", "interp")],
         "Keep what happened and what you make of it in separate columns, so that the interpretation can be checked against the record.",
         "sec-09-observations-and-documents", "Observations and documents"),
],
10: [
    sort("Anonymity or confidentiality?", "Sort each statement to the term it describes.",
         [("anon", "Anonymity"), ("conf", "Confidentiality")],
         [("answers cannot be linked to persons — not even by the researcher", "anon"),
          ("the link exists but is protected and never revealed", "conf"),
          ("an anonymous online survey that collects no e-mail address", "anon"),
          ("recorded interviews with a separate key file (name ↔ P#)", "conf")],
         "Promise only what you can keep: a recorded interview can be confidential, but it cannot be anonymous.",
         "sec-10-participants-rights", "Participants' rights"),
    sort("The consent form", "Which requirement does each sentence meet?",
         [("who", "Who and purpose"), ("what", "What it involves"), ("data", "Data, storage, deletion"), ("vol", "Voluntariness, withdrawal")],
         [("\"We are three master's students investigating how developers handle security warnings.\"", "who"),
          ("\"Participation means one recorded interview of 30–45 minutes about your daily work.\"", "what"),
          ("\"Recordings are stored on university-approved storage, accessible to the group only, and deleted after transcription.\"", "data"),
          ("\"Participation is voluntary; you may withdraw at any time without giving a reason.\"", "vol")],
         "SIKT provides consent-form templates — use them rather than writing your own from scratch.",
         "sec-10-worked-examples-and-tables", "Consent and anonymisation"),
    pick("Personal data?", "Select the items that count as personal data.",
         [("An e-mail address used to send the survey link", True),
          ("An audio recording of an interview", True),
          ("A job title plus company name in a small firm", True),
          ("Aggregated counts of operating-system versions", False)],
         "Personal data is any information relating to an identified or identifiable person — including indirect identification.",
         "sec-10-the-law", "The law"),
    order("Before the data arrives", "Click the steps in the order in which they happen.",
          ["Decide whether you will process personal data", "Notify SIKT before data collection starts", "Obtain informed consent", "Collect the data", "Delete the recordings after transcription"],
          "The SIKT notification comes before collection; the data management plan says where each kind of data lives, who can access it, and when it is deleted.",
          "sec-10-sikt-in-practice", "SIKT in practice"),
],
11: [
    sort("What the examiners look for", "Drag each expectation — and each typical overspend — to the essay part.",
         [("p1", "Part I"), ("p2", "Part II"), ("p3", "Part III"), ("p4", "Part IV")],
         [("One question, a clear hierarchy, justified relevance", "p1"),
          ("A documented, repeatable search; synthesis, not a list", "p2"),
          ("Choices argued: fit to question and resources, alternatives rejected with reasons", "p3"),
          ("Honest limitations, concrete ethics and privacy, a realistic plan", "p4"),
          ("Overspend: general background prose", "p1"),
          ("Overspend: textbook definitions", "p3")],
         "Roughly two, two and a half, three and two and a half pages — and each part has its own way of overspending.",
         "sec-11-part-by-part", "Part by part"),
    order("The golden thread", "Click the links of the chain in order.",
          ["Problem", "Question", "Strategy", "Methods", "Analysis"],
          "Each link answers to the previous one; where the thread breaks is where the examiner's first question will come from.",
          "sec-11-the-essay-as-argument", "The essay as argument"),
    sort("Describe or justify?", "Every methodological statement is a pair. Sort the halves.",
         [("desc", "Describe", "what, precisely"), ("just", "Justify", "why this, here")],
         [("An online questionnaire (12 items, Nettskjema) will be sent to all 60 client staff", "desc"),
          ("because SQ1 asks how widespread reuse is, which requires breadth across the whole organisation", "just"),
          ("The component library will be evaluated in a usability test (8 users, 5 tasks, SUS)", "desc"),
          ("because the research claim concerns developer-facing usability, not runtime performance", "just"),
          ("The incident will be studied as a single explanatory case", "desc"),
          ("because the question asks how recovery unfolded in context — depth over breadth", "just")],
         "The describe–justify pair, spoken, is also the answer to the oral exam's \"why this method?\".",
         "sec-11-writing-methodology", "Writing methodology"),
    sort("The recurring failures", "Match each symptom to the failure.",
         [("textbook", "Textbook methodology"), ("shop", "Shopping-list literature"), ("thread", "Broken thread"), ("ethics", "Afterthought ethics"), ("vague", "Vague plan")],
         [("Part III defines \"what a case study is\" for a page", "textbook"),
          ("paper-by-paper summary", "shop"),
          ("question and methods from different projects", "thread"),
          ("one generic ethics paragraph", "ethics"),
          ("\"some interviews will be conducted\"", "vague")],
         "Replace definitions with your justified choices, rewrite by concept, run the reviewer's test, make ethics concrete, give numbers.",
         "sec-11-failure-modes", "Failure modes"),
    pick("The AI declaration", "Which statements belong in a specific, honest AI declaration?",
         [("ChatGPT was used to brainstorm synonym candidates for the search string (Part II)", True),
          ("All sources were located, read and selected by the group", True),
          ("No participant data was entered into any AI tool", True),
          ("AI tools were used to some extent during the work", False)],
         "Vague looks evasive; specific — what tool, for what, and what it was not used for — looks honest.",
         "sec-11-worked-examples-and-tables", "Signposting, limitations and the AI declaration"),
],
12: [
    order("The pipeline", "Click the stages of the course's pipeline in order.",
          ["Problem and purpose", "Research question", "Literature review", "Strategy", "Methods and analysis", "Ethics and report"],
          "Twelve sessions, one pipeline — with the approach and worldview underneath every step.",
          "sec-12-the-course-in-one-picture", "The course in one picture"),
    sort("The running example, assembled", "Sort each element of the running example to the session that produced it.",
         [("s3", "Problem (S3)"), ("s4", "Question (S4)"), ("s5", "Literature (S5)"), ("s67", "Strategy (S6–7)"), ("s89", "Data (S8–9)"), ("s10", "Ethics (S10)")],
         [("employees reuse passwords despite training — SMBs carry the breach risk", "s3"),
          ("which factors are associated with password reuse among SMB employees?", "s4"),
          ("search string, log, criteria, PRISMA, concept matrix", "s5"),
          ("survey (SQ1) + interviews (SQ2) = mixed, explanatory sequential", "s67"),
          ("questionnaire, n ≈ 150; eight semi-structured interviews", "s89"),
          ("personal data: yes → SIKT; consent per template", "s10")],
         "Each row consumes the one above — the golden thread in action.",
         "sec-12-one-study-end-to-end", "One study end to end"),
    sort("Reproduction or judgement?", "What separates the grades: sort each description.",
         [("repro", "Reproduction"), ("judg", "Judgement")],
         [("Background and literature reported correctly", "repro"),
          ("One question with a hierarchy; a synthesis that argues", "judg"),
          ("Strategy and methods named and described", "repro"),
          ("Choices justified, alternatives rejected with reasons", "judg"),
          ("The essay presented", "repro"),
          ("The choices defended under questioning", "judg")],
         "Judgement, not reproduction, is what separates the grades.",
         "sec-12-the-essay-and-the-oral-exam", "The essay and the oral exam"),
    sort("Six strategies in one line each", "Match each one-liner to its strategy.",
         [("survey", "Survey"), ("dc", "Design and creation"), ("exp", "Experiment"), ("case", "Case study"), ("ar", "Action research"), ("ethno", "Ethnography")],
         [("breadth: patterns across many, sampling decides the claim", "survey"),
          ("learning via making — the research lives in the evaluation", "dc"),
          ("the only strategy that earns the word because", "exp"),
          ("depth in one setting; analytical generalisation", "case"),
          ("change practice in cycles, with the practitioners", "ar"),
          ("immersion; the unwritten rules", "ethno")],
         "Sessions 6 and 7 in six lines.",
         "sec-12-flashbacks-and-tables", "Flashbacks"),
    pick("Submission FAQ", "Select the statements that are true.",
         [("Tables count toward the ten pages", True),
          ("The research question may still be changed if Parts II–IV are updated to match", True),
          ("In the oral exam each group member must be able to defend every part", True),
          ("There is a minimum number of references", False),
          ("A pending SIKT answer blocks submission", False)],
         "No reference quota, and the plan is graded, not the approval letter.",
         "sec-12-the-essay-and-the-oral-exam", "The essay and the oral exam"),
],
}


def slug(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def main() -> None:
    for no, exercises in EX.items():
        nn = f"{no:02d}"
        out = [f"<!-- Interactive exercises for chapter {no}; generated by tools/make_interactive.py, included from chapters/{nn}-{SLUGS[no]}.qmd -->", ""]
        for ex in exercises:
            eid = f"exr-{nn}-{slug(ex['title'])}-interactive"
            out.append(f"::: {{#{eid}}}")
            out.append(f"## {ex['title']}, interactive")
            out.append("")
            out.append(ex["intro"] + " Then press **Check**.")
            out.append("")
            out.append("```{=html}")
            out.append(f'<div class="grc-ex" data-type="{ex["type"]}">')
            out.append('<script type="application/json">')
            out.append(json.dumps(ex["cfg"], ensure_ascii=False, indent=1))
            out.append("</script>")
            out.append("</div>")
            out.append("```")
            out.append(":::")
            out.append("")
        (ROOT / "chapters" / f"_{nn}-interactive.qmd").write_text("\n".join(out))
        print(f"chapters/_{nn}-interactive.qmd: {len(exercises)} exercises")


if __name__ == "__main__":
    main()
